version: '3'
services:

  opendaylight:
    image: odl
    stdin_open: true
    tty: true
    networks:
      netconf:
        ipv4_address: 172.0.0.4

  sysrepo:
    image: sysrepo/sysrepo-netopeer2
    volumes:
      - ./src:/opt/dev/netopeer2-src
    ports:
      - 830:830
    networks:
      netconf:
        ipv4_address: 172.0.0.2

networks:
  netconf:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/24

