version: '3'
services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  postgresql:
    restart: always
    environment:
      PGPASSWORD: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
volumes:
  db:
