version: '3'
services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  postgresql:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./salt.sql:/docker-entrypoint-initdb.d/salt.sql
volumes:
  salt.sql:
